name: Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches-ignore: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: yarn install --frozen-lockfile
    - name: Build and validate
      run: yarn build
      env:
        WEB3_PROVIDER_URL: ${{ secrets.WEB3_PROVIDER_URL }}
        ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
    - name: Run tests
      run: yarn test
      env:
        WEB3_PROVIDER_URL: ${{ secrets.WEB3_PROVIDER_URL }}
        ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
